sonar.projectKey=green-energy
sonar.projectName=Green Energy
sonar.sources=backend/app,frontend/src
sonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/tests/**,**/*.spec.js
sonar.sourceEncoding=UTF-8

# optional coverage reports if you add them later
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info